# --- Day 3: Lobby ---

You descend a short staircase, enter the surprisingly vast lobby, and are quickly cleared by the security checkpoint. When you get to the main elevators, however, you discover that each one has a red light above it: they're all **offline**.

"Sorry about that," an Elf apologizes as she tinkers with a nearby control panel. "Some kind of electrical surge seems to have fried them. I'll try to get them online soon."

You explain your need to get further underground. "Well, you could at least take the escalator down to the printing department, not that you'd get much further than that without the elevators working. That is, you could if the escalator weren't also offline."

"But, don't worry! It's not fried; it just needs power. Maybe you can get it running while I keep working on the elevators."

There are batteries nearby that can supply emergency power to the escalator for just such an occasion. The batteries are each labeled with their **joltage** rating, a value from `1` to `9`. You make a note of their joltage ratings (your puzzle input). For example:

```
987654321111111
811111111111119
234234234234278
818181911112111
```

The batteries are arranged into **banks**; each line of digits in your input corresponds to a single bank of batteries. Within each bank, you need to turn on **exactly two** batteries; the joltage that the bank produces is equal to the number formed by the digits on the batteries you've turned on. For example, if you have a bank like 12345 and you turn on batteries 2 and 4, the bank would produce 24 jolts. (You cannot rearrange batteries.)

You'll need to find the largest possible joltage each bank can produce. In the above example:

- In `987654321111111`, you can make the largest joltage possible, `98`, by turning on the first two batteries.
- In `811111111111119`, you can make the largest joltage possible by turning on the batteries labeled `8` and `9`, producing 89 jolts.
- In `234234234234278`, you can make `78` by turning on the last two batteries (marked `7` and `8`).
- In `818181911112111`, the largest joltage you can produce is `92`.

The total output joltage is the sum of the maximum joltage from each bank, so in this example, the total output joltage is `98 + 89 + 78 + 92 = 357`.

There are many batteries in front of you. Find the maximum joltage possible from each bank; **what is the total output joltage?**

In [1]:
# get inputs

with open("inputs/day_03.txt") as file:
    my_inputs = file.read().splitlines()
    
with open("inputs/day_03_test.txt") as file:
    test_inputs = file.read().splitlines()

In [2]:
test_inputs

['987654321111111', '811111111111119', '234234234234278', '818181911112111']

In [16]:
list(test_inputs[0])

['9', '8', '7', '6', '5', '4', '3', '2', '1', '1', '1', '1', '1', '1', '1']

In [14]:
def find_max_voltage(bank:str):
    bank_digits = list(bank)
    max_first_digit = max(bank_digits[:-1]) # exclude final digit
    max_first_digit_position = bank_digits.index(max_first_digit)
    max_second_digit = max(bank_digits[max_first_digit_position+1:])
    max_voltage = int(max_first_digit + max_second_digit)
    return max_voltage

In [19]:
find_max_voltage(test_inputs[3])

92

In [20]:
def calculate_total_output_voltage(banks:list):
    total_voltage = 0
    for bank in banks:
        max_voltage = find_max_voltage(bank)
        total_voltage += max_voltage
    return total_voltage

In [21]:
calculate_total_output_voltage(test_inputs)

357

In [22]:
calculate_total_output_voltage(my_inputs)

17321

# --- Part Two ---
The escalator doesn't move. The Elf explains that it probably needs more joltage to overcome the static friction of the system and hits the big red "joltage limit safety override" button. You lose count of the number of times she needs to confirm "yes, I'm sure" and decorate the lobby a bit while you wait.

Now, you need to make the largest joltage by turning on exactly twelve batteries within each bank.

The joltage output for the bank is still the number formed by the digits of the batteries you've turned on; the only difference is that now there will be 12 digits in each bank's joltage output instead of two.

Consider again the example from before:

```
987654321111111
811111111111119
234234234234278
818181911112111
```

Now, the joltages are much larger:

- In `987654321111111`, the largest joltage can be found by turning on everything except some 1s at the end to produce `987654321111`.
- In the digit sequence `811111111111119`, the largest joltage can be found by turning on everything except some 1s, producing `811111111119`.
- In `234234234234278`, the largest joltage can be found by turning on everything except a 2 battery, a 3 battery, and another 2 battery near the start to produce `434234234278`.
- In `818181911112111`, the joltage `888911112111` is produced by turning on everything except some 1s near the front.
- The total output joltage is now much larger: `987654321111 + 811111111119 + 434234234278 + 888911112111 = 3121910778619`.

**What is the new total output joltage?**

In [79]:
def find_max_voltage_v2(bank:str):
    bank_digits = list(bank)
    digits_left = 12
    max_voltage_digits = ''
    starting_position = 0
    while digits_left > 0:
        if digits_left == 1:
            next_digit = max(bank_digits[starting_position:])
            next_digit_position = bank_digits.index(next_digit, starting_position)
        else:
            next_digit = max(bank_digits[starting_position:-digits_left+1])
            next_digit_position = bank_digits.index(next_digit, starting_position, -digits_left+1)
        max_voltage_digits += next_digit
        starting_position = next_digit_position + 1
        digits_left -= 1

    max_voltage = int(max_voltage_digits)
    return max_voltage

In [76]:
find_max_voltage_v2(test_inputs[1])

811111111119

In [80]:
def calculate_total_output_voltage_v2(banks:list):
    total_voltage = 0
    for bank in banks:
        max_voltage = find_max_voltage_v2(bank)
        total_voltage += max_voltage
    return total_voltage

In [81]:
calculate_total_output_voltage_v2(test_inputs)

3121910778619

In [82]:
calculate_total_output_voltage_v2(my_inputs)

171989894144198